[package]
name = "numake"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "1.0.82" }
clap = { version = "4.5.4", features = ["derive"] }
dunce = { version = "1.0.4" }
mlua = { version = "0.9.7", features = ["vendored", "luau", "luau-jit"] }
pathdiff = { version = "0.2.1" }
reqwest = { version = "0.12.4", features = ["blocking"] }
serde = { version = "1.0.199", features = ["derive"] }
serde_json = { version = "1.0.116" }
sha256 = { version = "1.5.0" }
tempfile = { version = "3.10.1" }
toml = { version = "0.8.12" }
zip = { version = "1.1.1", features = ["deflate-zlib-ng", "deflate-zopfli", "zstd", "lzma", "bzip2", "time", "chrono", "deflate64", "aes-crypto"] }
