unstable_features = true
brace_style = "AlwaysNextLine"
combine_control_expr = false
edition = "2021"
fn_params_layout = "Vertical"
fn_single_line = true
force_multiline_blocks = true
hard_tabs = true
imports_layout = "Vertical"
imports_granularity = "Crate"
reorder_impl_items = true
group_imports = "StdExternalCrate"
spaces_around_ranges = true
struct_lit_single_line = false
